import{a as y,S as f,i as u}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=i(t);fetch(t.href,a)}})();const n=new URLSearchParams({key:"44564788-7b6b025cc245aa7d761eb8e00",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15});async function m(e){try{return(await y.get(e)).data}catch(r){console.log(r)}}const L=new f(".gallery a",{captionsData:"alt",captionDelay:250});function g(e,r){r.insertAdjacentHTML("beforeend",b(e)),L.refresh()}function b(e){return e.hits.map(({webformatURL:r,largeImageURL:i,tags:o,likes:t,views:a,comments:l,downloads:h})=>`<li>
                <a href="${i}"><img src='${r}' alt='${o}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${t}</p></div>
                    <div class="item"><h3>Views</h3><p>${a}</p></div>
                    <div class="item"><h3>Comments</h3><p>${l}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${h}</p></div>
                </div>
            </li>`).join("")}const c={addloader({loader:e}){e.classList.remove("hidden")},delLoader({loader:e}){e.classList.add("hidden")}},p={addloadMore(e){e.classList.remove("hidden")},delLoadMore(e){e.classList.add("hidden")}};function v(){const i=document.querySelector(".gallery li").getBoundingClientRect().height*2+24*3;window.scrollBy({top:i,behavior:"smooth"})}const s={form:document.querySelector("#form-request"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnEl:document.querySelector("button[data-action=submit]"),btnLoad:document.querySelector("button[data-action=load-more]")},d={emptyHits:"We're sorry, but you've reached the end of search results.",userTextEmpty:"Search field must be filled",invalidRequest:"Sorry, there are no images matching your search query. Please try again!"};s.form.addEventListener("submit",async e=>{e.preventDefault(),s.gallery.innerHTML="";const r=e.target.query.value.trim();if(!r){u.warning({title:"Attention!",message:d.userTextEmpty,messageSize:"16",position:"topRight",close:!1,displayMode:1});return}n.set("q",r),n.set("page",1),c.addloader(s);const i="https://pixabay.com/api/?"+n;try{const o=await m(i);let t=n.get("page");const a=Math.ceil(o.totalHits/n.get("per_page"));if(t<a?p.addloadMore(s.btnLoad):p.delLoadMore(s.btnLoad),!o.totalHits)throw new Error(d.invalidRequest);s.gallery.innerHTML="",g(o,s.gallery)}catch(o){u.error({title:"Error!",message:o.message,messageSize:"16",position:"topRight",close:!1,displayMode:1})}c.delLoader(s)});s.btnLoad.addEventListener("click",async e=>{e.preventDefault(),c.addloader(s);let r=n.get("page");n.set("page",++r);const i="https://pixabay.com/api/?"+n;try{const o=await m(i);if(!o.totalHits)throw new Error(d.invalidRequest);const t=Math.ceil(o.totalHits/n.get("per_page"));if(g(o,s.gallery),v(),r>=t)throw p.delLoadMore(s.btnLoad),new Error("No more pages")}catch(o){console.log(o),u.error({title:"Error!",message:d.emptyHits,messageSize:"16",position:"topRight",close:!1,displayMode:1})}e.target.reset,c.delLoader(s)});
//# sourceMappingURL=commonHelpers.js.map
